export enum APPOINTMENT_STATUS {
  "PENDING" = "PENDING",
  ONGOING = "ONGOING",
  NO_SHOW = "NO_SHOW",
  CONFIRMED = "CONFIRMED",
  DOCTOR_CANCELLATION_REQUESTED = "DOCTOR_CANCELLATION_REQUESTED",
  CANCELLED_BY_DOCTOR = "CANCELLED_BY_DOCTOR",
  CANCELLED_BY_PATIENT = "CANCELLED_BY_PATIENT",
  COMPLETED = "COMPLETED",
  SKIPPED = "SKIPPED",
  EXPIRED = "EXPIRED",
}
export enum PAYMENT_STATUS {
  PENDING = "PENDING",
  REFUNDED = "REFUNDED",
  PAID = "PAID",
}


export enum CONSULTATION_TYPE {
  ONLINE = "ONLINE",
  CLINIC = "CLINIC",
}

export enum BOOKING_PERIOD {
  WEEK = 'WEEK',
  MONTH = 'MONTH',
  YEAR = 'YEAR'
}