export enum PDF_TYPE {
  PATIENT_APPOINTMENT = "PATIENT_APPOINTMENT",
  PAYMENT_RECEIPT = "PAYMENT_RECEIPT",
  DOCTOR_APPOINTMENT = "DOCTOR_APPOINTMENT",
  PATIENT_TRANSACTION = "PATIENT_TRANSACTION",
  DOCTOR_TRANSACTION = "DOCTOR_TRANSACTION",
  ADMIN_REVENUE = "ADMIN_REVENUE",
    PATIENT_INVOICE='PATIENT_INVOICE'

}
