version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    command: ["mongod", "--quiet"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
     - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./server:/home/node/app
      - /home/node/app/node_modules
    container_name: backend
    env_file:
      - ./server/.env
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: sh -c "npm run lint && npm run dev"
    depends_on:
      - redis
      - mongo

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./client:/home/next/
      - /home/next/node_modules
    container_name: frontend
    ports:
      - '3000:3000'
    command: sh -c "npm run lint && npm run dev"
    depends_on:
      - backend


volumes:
  mongo_data: