
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

    depends_on:
      - frontend
      - backend
      - grafana

    networks:
      - app


  backend:
    image: jassymon/helio-backend:latest
    
    container_name: backend
    expose:
      - "5000"

    restart: unless-stopped

    env_file:
      - ./server/.env

    depends_on:
      - redis
      - qdrant

    networks:
      - app

  worker:
    image: jassymon/helio-worker:latest

    container_name: worker

    restart: unless-stopped

    env_file:
      - ./server/.env

    command: node dist/workers/emailWorker.js

    depends_on:
      - redis
      - backend
    
    networks:
      - app

  frontend:
    image: jassymon/helio-frontend:latest
    container_name: frontend

    restart: unless-stopped

    environment:
      - SERVER_BACKEND_URL=value

    expose:
      - "3000"

    depends_on:
      - backend

    networks:
      - app

  redis:
    image: redis:7-alpine
    container_name: redis

    restart: unless-stopped

    volumes:
      - redis_data:/data

    networks:
      - app

  prom-server:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped

    expose:
      - "9090"

    volumes:
      - ./prometheus/prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"

    depends_on:
      - backend
    networks:
      - app

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped

    expose:
      - "3000"

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - prom-server
      - loki
    networks:
      - app

  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped

    expose:
      - "3100"

    volumes:
      - loki_data:/loki

    networks:
      - app


  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    
    restart: always

    expose:
      - "6333"

    volumes:
      - qdrant_data:/qdrant/storage

    networks:
      - app

  gotenberg:
    image : gotenberg/gotenberg:8-chromium
    expose:
      - "3000"
    networks:
      - app


networks:
  app:

volumes:
  redis_data:
  qdrant_data:
  prometheus_data:
  grafana_data:
  loki_data:
