version: '3.9'

services:

  prom-server:
    image: prom/prometheus
    container_name: prometheus
    expose: 
      - "9090"
    volumes:
      - ./prometheus/prometheus-config.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - prom-server
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki
    container_name : loki
    expose:
      - "3100"
    restart: unless-stopped
    volumes:
      - loki_data:/loki

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always

    ports:
      - "80:80"
      - "443:443"
      - "9090:9090"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

    depends_on:
      - frontend
      - backend


  mongo:
    image: mongo:6
    container_name: mongo_db
    command: >
      mongod --replSet rs0 --keyFile /etc/mongo-keyfile --bind_ip_all --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
      - mongo_data:/data/db
      - mongo_config:/data/configdb

    restart: always
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) }" | mongosh --port 27017 -u admin -p secret --authenticationDatabase admin
      interval: 10s
      timeout: 5s
      retries: 2

  redis:
    image: redis:7
    container_name: redis_cache
    expose:
      - "6379"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./server:/app
      - backend_node_modules:/app/node_modules
    container_name: backend
    env_file:
      - ./server/.env
    expose:
       - '5000'
    command: sh -c "npm run eslint-fix && npm run dev"
    depends_on:
      - mongo
      - redis
      

  worker:
    container_name: worker
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./server:/app
      - backend_node_modules:/home/node/app/node_modules
    env_file:
      - ./server/.env
    command: npx tsx src/workers/emailWorker.ts
    depends_on:
      - redis
      - backend

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./client:/app
      - frontend_node_modules:/app/node_modules
    expose:
      - '3000'
    command: sh -c "npm run eslint-fix && npm run dev"
    depends_on:
      - backend

  gotenberg:
    container_name: gotenberg
    image : gotenberg/gotenberg:8-chromium
    expose:
      - "3000"

  qdrant:
    container_name: qdrant
    image : qdrant/qdrant
    expose:
      - "6333"

volumes:
  mongo_config:
    name: my_mongo_config

  mongo_data:
    name: my_mongo_data

  backend_node_modules:
    name: backend_node_modules

  frontend_node_modules:
    name: frontend_node_modules

  prometheus_data:
    name: prometheus_data

  grafana_data:
    name: grafana_data

  loki_data:
    name: loki_data
