export enum APPOINTMENT_STATUS {
  PENDING = "PENDING",
  ONGOING = "ONGOING",
  NO_SHOW = "NO_SHOW",
  CONFIRMED = "CONFIRMED",
  DOCTOR_CANCELLATION_REQUESTED = "DOCTOR_CANCELLATION_REQUESTED",
  CANCELLED_BY_DOCTOR = "CANCELLED_BY_DOCTOR",
  CANCELLED_BY_PATIENT = "CANCELLED_BY_PATIENT",
  COMPLETED = "COMPLETED",
  SKIPPED = "SKIPPED",
  EXPIRED = "EXPIRED",
}

export enum PAYMENT_STATUS {
  PENDING = "PENDING",
  REFUND_PENDING = "REFUND_PENDING",
  REFUNDED = "REFUNDED",
  PAID = "PAID",
  FAILED = "FAILED",
  REFUND_FAILED = "REFUND_FAILED",
}

export enum PAYMENT_TYPE {
  WALLET = "WALLET",
  RAZORPAY = "RAZORPAY",
}
