export enum APPOINTMENT_STATUS {
  "PENDING" = "PENDING",
  ONGOING = "ONGOING",
  NO_SHOW = "NO_SHOW",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
}

export enum PAYMENT_STATUS {
  PENDING = "PENDING",
  REFUNDED = "REFUNDED",
  PAID = "PAID",
}

export enum PAYMENT_TYPE {
  WALLET = "WALLET",
  RAZORPAY = "RAZORPAY",
}
