name: Deploy Helio to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend
        run: |
            docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/helio-backend:latest \
            ./server
      
      - name: Build Worker
        run: |
             docker build \
             -t ${{ secrets.DOCKER_USERNAME }}/helio-worker:latest \
             ./server

      - name: Build Frontend
        run: |
             docker build \
             -t ${{ secrets.DOCKER_USERNAME }}/helio-frontend:latest \
             ./client

      - name: Push Images
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/helio-backend:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/helio-worker:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/helio-frontend:latest


      - name: Deploy EC2
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/helio
            docker compose -f docker-compose.production.yml pull
            docker compose -f docker-compose.production.yml up -d
            docker image prune -f